##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Copyright © dev-cetera.com & contributors.
##
## The use of this source code is governed by an MIT-style license described in
## the LICENSE file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_pod
homepage: https://dev-cetera.com/
funding:
- https://www.buymeacoffee.com/dev_cetera
- https://www.patreon.com/c/robelator
- https://github.com/sponsors/robelator
- https://www.patreon.com/c/robelator
- https://github.com/sponsors/robelator
- https://www.buymeacoffee.com/dev_cetera
description: A package offering tools to manage app state using ValueListenable objects called Pods.
version: 0.18.15
topics:
  - bloc
  - provider
  - redux
  - riverpod
  - state-management

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7
  meta: ^1.16.0
  shared_preferences: ^2.5.4

  df_debouncer: ^0.4.16
  df_log: ^0.3.30
  df_safer_dart: ^0.17.8

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_lints: ^6.0.0
  custom_lint: ^0.7.6
  df_safer_dart_lints: ^0.3.3

